data = {
    "Top Rated": [
        {
            "id": "tt17543878",
            "title": "Arkadas Canlisi",
            "rating": 9.6,
            "voteCount": 6205,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYjg5MDllNzEtNzJjYi00Yzc0LWE5MmEtOGE0NzQwZDdhOWZjXkEyXkFqcGc@._V1_.jpg",
            "country": "TR",
            "language": "('tr',)",
            "type": 1,
        },
        {
            "id": "tt31369068",
            "title": "Bi' Kahve 2 Sohbet",
            "rating": 9.6,
            "voteCount": 6588,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYTIxNzI2MDktNjE0Zi00NTMxLTg1ZDItYzhkMmZhZjY0Y2U2XkEyXkFqcGc@._V1_.jpg",
            "country": "TR",
            "language": "('tr',)",
            "type": 1,
        },
        {
            "id": "tt32315359",
            "title": "Cumartesi-Pazar Surpriz",
            "rating": 9.5,
            "voteCount": 7948,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZTcwYWFkMDItZjNkMi00NzY1LWI0ZjctNTc3MzkyZGY3OWVmXkEyXkFqcGc@._V1_.jpg",
            "country": "TR",
            "language": "en",
            "type": 1,
        },
        {
            "id": "tt0903747",
            "title": "Breaking Bad",
            "rating": 9.5,
            "voteCount": 2291554,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 1,
        },
        {
            "id": "tt5152226",
            "title": "Tree of Life",
            "rating": 9.4,
            "voteCount": 17086,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZTkyYTM4ZTAtYTcxYy00YzlhLWI3YmQtNjc4Njk4OTM0MTQxXkEyXkFqcGc@._V1_.jpg",
            "country": "TR",
            "language": "('tr',)",
            "type": 1,
        },
        {
            "id": "tt0417299",
            "title": "Avatar: The Last Airbender",
            "rating": 9.3,
            "voteCount": 399643,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMDMwMThjYWYtY2Q2OS00OGM2LTlkODQtNDJlZTZmMjAyYmFhXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 1,
        },
        {
            "id": "tt0111161",
            "title": "The Shawshank Redemption",
            "rating": 9.3,
            "voteCount": 3015054,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt2348531",
            "title": "Half in the Bag",
            "rating": 9.3,
            "voteCount": 5625,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BNzhjZWZiYzgtNTY2OS00MzZiLWJhY2YtMThjNGE0MDgzZjYwXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 1,
        },
        {
            "id": "tt7678620",
            "title": "Bluey",
            "rating": 9.3,
            "voteCount": 36862,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYWU1YmQzMjEtMDNjOS00MGIyLWExY2ItZDAzNmU5NWViMGZmXkEyXkFqcGc@._V1_.jpg",
            "country": "AU",
            "language": "('en',)",
            "type": 1,
        },
        {
            "id": "tt2147999",
            "title": "Devon Ke Dev... Mahadev",
            "rating": 9.3,
            "voteCount": 5220,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZjQxODUzZTctNTIyMy00NTQxLWEzOTQtYWU3MWJhNGQzMTQxXkEyXkFqcGc@._V1_.jpg",
            "country": "IN",
            "language": "('hi',)",
            "type": 1,
        },
    ],
    "Action Movies": [
        {
            "id": "tt0006206",
            "title": "Les Vampires",
            "rating": 7.3,
            "voteCount": 5639,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMTc1NTY3NDIzNl5BMl5BanBnXkFtZTgwNTIyODg5MTE@._V1_.jpg",
            "country": "FR",
            "language": "zxx",
            "type": 0,
        },
        {
            "id": "tt0079315",
            "title": "The Fearless Hyena",
            "rating": 6.6,
            "voteCount": 5682,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BODVkMjAxODEtNWZjMy00NTA1LThhNDItMGMxYjI3NWQ0MjMxXkEyXkFqcGc@._V1_.jpg",
            "country": "HK",
            "language": "('yue',)",
            "type": 0,
        },
        {
            "id": "tt0079336",
            "title": "The In-Laws",
            "rating": 7.3,
            "voteCount": 10485,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZjIyOWRiZDYtM2M0YS00NWJjLWJiMzAtZGVkNzlkN2Q5MDZkXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0079351",
            "title": "I'm for the Hippopotamus",
            "rating": 6.6,
            "voteCount": 9769,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BM2JlNjI3Y2ItYzQ2MC00Nzg0LWE4MzMtM2RhN2Y2NzI1ODcyXkEyXkFqcGc@._V1_.jpg",
            "country": "IT",
            "language": "('it',)",
            "type": 0,
        },
        {
            "id": "tt0079501",
            "title": "Mad Max",
            "rating": 6.8,
            "voteCount": 237091,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMTM4Mjg5ODEzMV5BMl5BanBnXkFtZTcwMDc3NDk0NA@@._V1_.jpg",
            "country": "AU",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0080120",
            "title": "The Warriors",
            "rating": 7.5,
            "voteCount": 114697,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYjAzNTNlMTgtYzdlYi00NGViLWIwNzUtNjc3MDg1ZTAxNjc3XkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0080179",
            "title": "Drunken Master",
            "rating": 7.4,
            "voteCount": 45505,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMGVjNzA2Y2QtNzNlOC00ODE2LWE3NDEtMzE4NzUwNjdhZWQzXkEyXkFqcGc@._V1_.jpg",
            "country": "HK",
            "language": "('yue',)",
            "type": 0,
        },
        {
            "id": "tt0080240",
            "title": "Magnum, P.I.",
            "rating": 7.5,
            "voteCount": 30217,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZTJlNTQ5ZDktNmU4YS00NjllLWIwY2QtNmM4YTI1MWVkMWZiXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 1,
        },
        {
            "id": "tt0080684",
            "title": "Star Wars: Episode V - The Empire Strikes Back",
            "rating": 8.7,
            "voteCount": 1429042,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0080736",
            "title": "The Final Countdown",
            "rating": 6.7,
            "voteCount": 28256,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYjljZWJmOTktZGQyNi00NzFlLTk4ZmMtYzdjM2IxZDZiYjYyXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
    ],
    "Comedy Movies": [
        {
            "id": "tt0078813",
            "title": "The Miser",
            "rating": 6.6,
            "voteCount": 5387,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BODRhMjAzNzItYjFlNy00YjM1LTlhZDktMWZhMmQzMmI5NzUwXkEyXkFqcGc@._V1_.jpg",
            "country": "FR",
            "language": "('fr',)",
            "type": 0,
        },
        {
            "id": "tt0078841",
            "title": "Being There",
            "rating": 7.9,
            "voteCount": 80033,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMDQ2MWVhMDMtOTJmZi00ZGZmLTgxZDMtYTM4NDY2Nzc1NDA1XkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0078902",
            "title": "Breaking Away",
            "rating": 7.7,
            "voteCount": 26406,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BYTNkMTA4YzktNmE3Mi00NjdjLWE4MzAtZjcwOTVmYmMxNGIwXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0078907",
            "title": "French Fried Vacation 2",
            "rating": 7.4,
            "voteCount": 9569,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMTQzMDAxNDYwOV5BMl5BanBnXkFtZTgwNTE2MjkwMzE@._V1_.jpg",
            "country": "FR",
            "language": "('fr',)",
            "type": 0,
        },
        {
            "id": "tt0078913",
            "title": "Buffet Froid",
            "rating": 7.2,
            "voteCount": 6885,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BMmM3OWQxMWEtNDAyNy00ZmJhLTkxN2ItNmRlZmI2NTMzMzJiXkEyXkFqcGc@._V1_.jpg",
            "country": "FR",
            "language": "('fr',)",
            "type": 0,
        },
        {
            "id": "tt0079221",
            "title": "Gol Maal",
            "rating": 8.5,
            "voteCount": 21215,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BNjc2ZGI2MTYtMjkzYi00NjMxLThmMmQtOGVkN2IxMjM4ZjlmXkEyXkFqcGc@._V1_.jpg",
            "country": "IN",
            "language": "('hi',)",
            "type": 0,
        },
        {
            "id": "tt0079261",
            "title": "Hair",
            "rating": 7.5,
            "voteCount": 42368,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BODUzNjUzNzIzM15BMl5BanBnXkFtZTcwMjc4MjkzNA@@._V1_.jpg",
            "country": "XWG",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0079315",
            "title": "The Fearless Hyena",
            "rating": 6.6,
            "voteCount": 5682,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BODVkMjAxODEtNWZjMy00NTA1LThhNDItMGMxYjI3NWQ0MjMxXkEyXkFqcGc@._V1_.jpg",
            "country": "HK",
            "language": "('yue',)",
            "type": 0,
        },
        {
            "id": "tt0079336",
            "title": "The In-Laws",
            "rating": 7.3,
            "voteCount": 10485,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BZjIyOWRiZDYtM2M0YS00NWJjLWJiMzAtZGVkNzlkN2Q5MDZkXkEyXkFqcGc@._V1_.jpg",
            "country": "US",
            "language": "('en',)",
            "type": 0,
        },
        {
            "id": "tt0079351",
            "title": "I'm for the Hippopotamus",
            "rating": 6.6,
            "voteCount": 9769,
            "imageUrl": "https://m.media-amazon.com/images/M/MV5BM2JlNjI3Y2ItYzQ2MC00Nzg0LWE4MzMtM2RhN2Y2NzI1ODcyXkEyXkFqcGc@._V1_.jpg",
            "country": "IT",
            "language": "('it',)",
            "type": 0,
        },
    ],
}


for key, val in data.items():
    for movie in val:
        movie["imageUrl"] = movie["imageUrl"].replace("_V1_", "_V0_UY248_")

print(data)
